### ISSUE TITLE
Infeasable permission request

### ISSUE THREAD

**Issue by jonigkeit** [openEHR/adl-designer#13]
Why would the adl-designer need complete access to all public repositories?

Quoting `https://help.github.com/articles/connecting-with-third-party-applications/#repositories`

> Repository information includes the names of contributors, the branches you've created, and the actual files within your repository. Applications can request access for either public or private repositories on a user-wide level. **This is one of the most expansive configurations you can permit, so accept it with caution!**

**Comment by markopi64** [comment]
Currently the expected workflow is:
  - create a fork of a common archetype repository
  - select your fork as the active repository and work on that fork
  - create a pull request to incorporate your changes to the common archetype repository

Unfortunately, GitHub permission granularity does not allow to set access rights for a particular repository. You can grant permissions from a set of scopes defined at https://developer.github.com/v3/oauth/#scopes
We are using scope public_repo, which is the least invasive permission that lets us create a fork and have write access to it.


The current workflow has these benefits:
  - common archetype repository does not have write access, all changes to it must be done with a pull request
  - avoid merging issues on adl-designer
  - no local storage, all saves are pushed immediately to GitHub

The main issue is relatively broad access requirements. You are not the first person who is bothered by that.

We are still looking into alternatives, including avoiding GitHub and using git directly. But the current priority is making a better gui.
