### ISSUE TITLE
use_archetype does not include id-code

### ISSUE THREAD

**Issue by pieterbos** [openEHR/adl-designer#2]
When creating a use_archetype statement in the adl-designer, the following is serialized to the .adlt file:
```adl
use_archetype OBSERVATION[openEHR-EHR-OBSERVATION.ovl-blood_pressure-blood_pressure-001.v1.0.0]
```

While according to the manual and grammar, it should include an id-code, like:

```adl
use_archetype OBSERVATION[id5, openEHR-EHR-OBSERVATION.ovl-blood_pressure-blood_pressure-001.v1.0.0]
```

**Comment by markopi64** [comment]
NodeId was included only when filling a slot. Now it should be fixed.

**Comment by pieterbos** [comment]
Confirmed, it has been fixed.
