### ISSUE TITLE
template_overlay serializes not according to spec, including metadata, language and description

### ISSUE THREAD

**Issue by pieterbos** [openEHR/adl-designer#4]
Not sure if this is an adl_designer or adl2-core issue, but:

According to the specs, the grammar for a template_overlay is:

```
adl_template_overlay: 'template_overlay'
        ARCHETYPE_HRID
    'specialize'
        ARCHETYPE_REF
    'definition'
        c_complex_object
    ('rules'
        assertion+)?
    'terminology'
        odin_text
    ;
```

However, adl-design outputs some extra information:
- metadata after 'template_overlay' with the adl and rm-version
- a language section
- a description
- perhaps more?

So it does not fully conform to the spec here and the output may not be parseable by other parsers.

**Comment by markopi64** [comment]
I removed extraneous data, should be ok now.

**Comment by pieterbos** [comment]
Tested. Mostly fixed, but not completely. It now serialized:

```
template_overlay (rm_release=1.0.2)
    openEHR-EHR-OBSERVATION.ovl-height-template-001.v1.0.0
```

The (rm_release=1.0.2) should not be present

**Comment by markopi64** [comment]
I removed rm_release as well

**Comment by pieterbos** [comment]
Thanks for the amazingly fast response - that solved the issue!

A coworker found another issue with opening templates saved by the designer, he will report it soon.
