### ISSUE TITLE
Cannot load template

### ISSUE THREAD

**Issue by steijgeler** [openEHR/adl-designer#5]
When creating a template, it cannot be loaded again. Steps to reproduce using the archetypes from openEHR CKM:

1. Create a new template (I used COMPOSITION.report-result as parent archetype)
2. Select an archetype for content (I selected OBSERVATION.height)
3. Save
4. Load doesn't work

I am getting a javascript error in am-model.js:294: ```Uncaught TypeError: Cannot read property 'code_string' of undefined```

The template overlay does not have an original_language set, so attempting to get the code_string gives an error.

This still happens after your fix to the template overlay segment a few minutes ago

**Comment by markopi64** [comment]
Should be fixed now

**Comment by steijgeler** [comment]
Yep, thanks!
