### ISSUE TITLE
Github application permissions excessive?

### ISSUE THREAD

**Issue by wolandscat** [openEHR/adl-designer#6]
I think the Designer is asking for every possible permission?
![image](https://cloud.githubusercontent.com/assets/1481744/11352009/c802a0d0-9231-11e5-9e04-e6e75adec06b.png)

**Comment by markopi** [comment]
I removed unnecessary permissions. Only access to public repositories is now required

**Comment by jonigkeit** [comment]
Why would you need complete access to public repositories ...
